spring:
  datasource:
    url: jdbc:postgresql://${SCHOOL_DB_HOST:localhost}:${SCHOOL_DB_PORT:5432}/${SCHOOL_DB_NAME:school}
    username: "postgres"
    password: "sql"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: none